// <auto-generated />
namespace EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DAA_M2M_CourseModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DAA_M2M_CourseModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202012031615549_DAA_M2M_CourseModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
