TRUNCATE TABLE MENUITEM

SELECT * from MENUITEM
SELECT * from [Order]
SELECT * from Customer

USE EF_DAA_One_One_Mapping
GO

ALTER DATABASE EF_DAA_One_Many_Mapping
SET SINGLE_USER 
WITH ROLLBACK IMMEDIATE
GO
DROP DATABASE EF_DAA_One_Many_Mapping
GO